version: '2'
services:
  balancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: /api/v1
        priority: 1
        protocol: http
        service: backend
        source_port: 80
        target_port: 8030
      - path: /
        priority: 2
        protocol: http
        service: frontend
        source_port: 80
        target_port: 3000
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  seed-db:
    scale: 1
    start_on_create: true
  backend:
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8030
      unhealthy_threshold: 3
      initializing_timeout: 20000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  frontend:
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 3000
      unhealthy_threshold: 3
      initializing_timeout: 10000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  db:
    scale: 1
    start_on_create: true
